steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/apipatient', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apipatient']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'apipatient', '--image', 'gcr.io/$PROJECT_ID/apipatient', '--platform', 'managed', '--region', 'asia-southeast2', '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/apipatient'
